DROP TABLE IF EXISTS favorites;

CREATE TABLE favorites (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    video_id INTEGER NOT NULL REFERENCES,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP




    --  favorites BOOLEAN DEFAULT false,